apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world-api-deployment
  labels:
    app: java-hello-world-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-hello-world-api
  template:
    metadata:
      labels:
        app: java-hello-world-api
    spec:
      containers:
      - name: java-hello-world-api
        image: luukvv/java-hello-world-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-hello-world-api-service
spec:
  selector:
    app: java-hello-world-api
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 32139